### ISSUE TITLE
Ion in/out folders- is "data" folder necessary?

### ISSUE THREAD

**Issue by daltskin** [lawrencegripper/ion#116]
Is the data folder necessary?

- ion/in/data
- ion/out/data

Why not just:

- ion/in
- ion/out

The meta file is already stored at the root of ion. @jjcollinge

**Comment by jjcollinge** [comment]
The input event metafile is stored at `in/eventmeta.json` and the output insights file is located at `out/insights.json`- if I dropped everything to root I wouldn't be able to differentiate between the intent of the file.

See: https://github.com/lawrencegripper/ion/blob/master/internal/app/handler/constants/constants.go#L20:2

**Comment by daltskin** [comment]
So is it ok if a module needs to store configuration data at ion/in?
Just trying to ascertain if ion/in parent folder is really only intended for the ion system.

**Comment by jjcollinge** [comment]
Sure, additional files can be stored at `ion/in` or anywhere else in the filesystem. By the time the module starts, the `ion/in` folder is not touched against by Ion
