### ISSUE TITLE
Ion CLI module creation

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/ion#122]
In order to improve the current local development experience I propose unifying the CLI for operating `ion` with that used to develop modules.

This could be implemented either in the `management` server by running it locally, or entirely in the CLI with no requirement for the management server.

If we do use the management server, to reduce the code impact on the existing Dispatcher we would develop a new local development component (may also be called a dispatcher) that the management API would use to orchestrate the local `ion` environment. 
Alternatively we add a similar component to the existing CLI and leave the management server as is.

The development experience should treat `events` as first class citizens and not bypass the initial trigger event.

The proposed workflow would look something similar to this:

`ion dev event create --event-type=new_image --files=file1.png,file2.png,file3.png --eventid=1234`
This command will then generate the required `event_event1234.json` and `context_event1234.json` files expected by the `handler` inside the local state store `~/.ion/store/events`.

The next step would be to prepare your module for execution:
`ion dev module prepare --basedir=ion --input-eventid=1234`
This command will prepare the environment in which to run the module, copying in the existing files generate by the previous step. It runs the preparer with the `--development` flag to ensure the `.dev` folder is created and local dataplane providers are used. Note, by providing the `--input-eventid` argument, this will make the CLI fetch the existing event, copy it's contents to the store and parse its contents in order to pass in the arguments to the handler as shown here: https://github.com/lawrencegripper/ion/blob/8156c8e05fa03b44ca68e7c9385709a14660ce0b/tools/ioncli/helpers/sidecar.go#L47:6

The module's environment is now set - the user can now run/debug their module manually in this context. NOTE: they must ensure to set the `ION_BASE_DIR` environment variable to the same directory used for the `--basedir` parameter on other commands i.e.
`ION_BASE_DIR=ion python3 mysupermodule.py`

Once their module has completed, the user can commit their module's output using:
`ion dev module commit --basedir=ion`
This will run the `committer` in development mode, using the local dataplane providers and development flag to dump the module's output to a `.dev` folder - once complete, the management server will copy the required files out of the `.dev` folder into a well structured format under `~/.ion/store`. (whether this is flat or hierarchical I am not sure yet.

The user will then be able to list the new events raised by their module by running:
`ion dev event list {--parent-eventid=1234}`
This will query the folder structure to return a list of matching events.

Base commands:
`ion dev module {prepare|commit|list|get|delete}`
`ion dev event {create|list|get}`

**Comment by lawrencegripper** [comment]
I starting look at what I could be used from the other CLI prototype but I think your right that all the CLI logic, when possible, should sit in the mangement api. 

I've started working on the shell of the tool with a couple of commands fleshed out which I can begin to get hooked up to the management api

**Comment by lawrencegripper** [comment]
Calling it a day now, got `ion module create` hooked up to the grpc stuff

**Comment by jjcollinge** [comment]
Additional changes: allow a development configuration to be passed in which sets a configurable output directory for the development files. This will save us duplicating copies of files around. The committer will simply dump out files into the provided directory. This can then be used by the CLI to directly build a directory structure it can work with.

This directory structure could look like the following:
```
~/ion/                                                           # top level dir
~/ion/config                                                 # ion cli config
~/ion/store/                                                 # store for state used by cli
~/ion/store/modules/                                  # store modules here
~/ion/store/modules/100000/                     # a root module directory
~/ion/store/modules/100000/_blobs/         # directory to store blobs
~/ion/store/modules/100000/_blobs/myfile.png
~/ion/store/modules/100000/_events/        # directory to store event files
~/ion/store/modules/100000/_events/event0.json
~/ion/store/modules/100000/_metadata/   # directory to store event metadata files
~/ion/store/modules/100000/_metadata/event0.json
~/ion/store/modules/100000/111111/        # a child module
~/ion/store/modules/100000/111000/        # another child module
~/ion/store/modules/100000/111000/101010 # a grandchild module
~/ion/store/modules/111111/                      # a sibling module
```
Although this isn't the most optimal method (if the tree gets big) we don't anticipate large local trees to be built.

`ion dev module list --parent-moduleid=10000` - recursively walks the FS tree matching on none '_' dir names.
`ion dev module get --moduleid=10000` - recursively searches the FS tree until it finds the folder and then outputs the dir contents matching '_'.
`ion dev module delete --moduleid=10000` - finds the directory and then deletes it and any sub directory (warning).
`ion dev module prepare --basedir=ion --input-eventid=1234` - runs the `handler` with action prepare and development enabled, this builds the module environment. Does not interact with the ion store.
`ion dev module commit --basedir=ion` - runs the `handler` with action commit and development enabled, this outputs development files directly into the ion store in the expected format.
`ion dev module init --event-type=new_image --files=file1.png,file2.png,file3.png --moduleid=1234` - this command initializes an "trigger" module, effectively a phony module that can be used as the input to the first module.

**Comment by lawrencegripper** [comment]
Related to #130 I want to add the following command:

`ion trace` under the `trace` command there will be options for following the output of an item by providing it's `correclationid` and also looking at the output of a particular module (say the last 15 runs it completed)

I think the following commands should do the trick `ion trace flow --correlationid uuidhere` and `ion trace module --modulename bob` maybe also a `ion trace logs --modulename bob --correlationid uuidhere` to retrieve the full console logs for a run. 

For the time being I'm going to start with `trace flow` as I think this is the most useful command

**Comment by lawrencegripper** [comment]
Closing this one out as the work in now in master
