### ISSUE TITLE
Handler `prepare` command fails with blob download issues

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/ion#137]
It looks like this should be a simple one, the handler prepare command gives the following output

```
"Starting handler\"\npanic: error during prepration failed to get blob 'f9a11562-e7fa-43ae-853c-429b9510c465-transcode-file.raw' with error 'storage: service returned error: StatusCode=404, ErrorCode=BlobNotFound, ErrorMessage=The specified blob does not exist
```

if you get the link from cosmos and hit it manually you get 

```xml
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:660b2421-801e-0069-1522-159142000000
Time:2018-07-06T12:12:43.7295193Z</Message><AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail></Error>
```

I think I just need to look at the signiture encoding to make sure it isn't getting messed with when the eventmeta is getting written to cosmos

**Comment by lawrencegripper** [comment]
Think I've got it.... from json.Marshal docs

```
// String values encode as JSON strings coerced to valid UTF-8,
// replacing invalid bytes with the Unicode replacement rune.
// The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e"
// to keep some browsers from misinterpreting JSON output as HTML.
// Ampersand "&" is also escaped to "\u0026" for the same reason.
// This escaping can be disabled using an Encoder that had SetEscapeHTML(false)
// called on it.
```

**Comment by lawrencegripper** [comment]
So that one is fixed up now the Sigs provided are valid, there is another bug though related to the blob url

Each time the blob provider is created there is a input and output prefix created. This appears to incorrectly cause the blob provider to download the blobs from the wrong location ... 

while the event meta has:

`/bdfbd2e6-9efc-41b7-bb7c-6395d3d80a0d/79d25901-cff1-4a93-88ac-6b4e4dbf369c-downloader-file.raw`

the preparer errors with:

`error during prepration failed to get blob '8d5b3679-cfd6-41f7-98b7-e147cc3e26a6-transcode-file.raw' with error 'storage: service returned error: StatusCode=404, ErrorCode=BlobNotFound, ErrorMessage=The specified blob does not exist.`

```
func getBlobProvider(config *Configuration) dataplane.BlobStorageProvider {
	if config.AzureBlobStorageProvider.Enabled {
		log.Info("using azure blob storage provider")
		c := config.AzureBlobStorageProvider
		azureBlob, err := azure.NewBlobStorage(c,
			helpers.JoinBlobPath(config.Context.ParentEventID, config.Context.Name),
			helpers.JoinBlobPath(config.Context.EventID, config.Context.Name))
		if err != nil {
			panic(fmt.Errorf("failed to establish blob storage with provider '%s', error: %+v", blobProviderAzureStorage, err))
		}
		return azureBlob
	} // else
``

**Comment by lawrencegripper** [comment]
Taking a look in more detail I think that this is because the `GetBlobData` method is trying to build a blob path from the filename where the filename is actually already a full url with a SAS token so it only needs to download it. Adding some more logs to validate this assumption. 

```
//GetBlobs gets each of the provided blobs from Azure Blob Storage
func (a *BlobStorage) GetBlobs(outputDir string, filePaths []string) error {
	containerName := a.containerName
	container := a.blobClient.GetContainerReference(containerName)
	for _, filePath := range filePaths {
		blobPath := helpers.JoinBlobPath(a.inputBlobPrefix, filePath)
		blobRef := container.GetBlobReference(blobPath)
		blob, err := blobRef.Get(&storage.GetBlobOptions{})
		if err != nil {
			return fmt.Errorf("failed to get blob '%s' from path '%s' with error '%+v'", blobPath, filePath, err)
		}
		var bytes []byte
		_, err = blob.Read(bytes)
		if err != nil {
			return fmt.Errorf("failed to read blob '%s' with error '%+v'", blobPath, err)
		}
		defer blob.Close() // nolint: errcheck
		outputFilePath := path.Join(outputDir, filePath)
		err = ioutil.WriteFile(outputFilePath, bytes, 0777)
		if err != nil {
			return fmt.Errorf("failed to write file '%s' with error '%+v'", outputFilePath, err)
		}
	}
	return nil
}
```

**Comment by lawrencegripper** [comment]
Nope that wasn't it. I think this is related to the context used by the committer being incorrect, rather than generating a new EventID the eventid used by the committer when working with blob data is actually the parenteventID this causes the blob read failure. 

I've moved the new context generation out of the `commitEvents` func into the `Commit` func so all methods such as insights and blobs have the correct context details.... hopefully testing now.

**Comment by lawrencegripper** [comment]
Ok that fixed that problem but now I see the following error:

```
time="2018-07-06T13:58:13Z" level=info msg="closing Preparer" correlationID=5abb39eb-4cee-46b2-97ad-d052c22e1a78 eventID=b48354ba-efb1-49e1-9748-02b0b5b6d91b name=transcode timestamp="2018-07-06 13:58:13.704250345 +0000 UTC m=+0.230058055"
panic: error during prepration failed to get blob '62ea785c-24c3-4bef-abb6-911a3ecaad89-transcode-file.raw' from path 'file.raw' with error 'storage: service returned error: StatusCode=404, ErrorCode=BlobNotFound, ErrorMessage=The specified blob does not exist.
```

So comparing the blob path it's searching for and the actual location you see 

```
5abb39eb-4cee-46b2-97ad-d052c22e1a78/62ea785c-24c3-4bef-abb6-911a3ecaad89-transcode-file.raw
5abb39eb-4cee-46b2-97ad-d052c22e1a78/62ea785c-24c3-4bef-abb6-911a3ecaad89-downloader-file.raw
```

This is because of this bit of code in handler/run.go:

```
		azureBlob, err := azure.NewBlobStorage(c,
			helpers.JoinBlobPath(config.Context.ParentEventID, config.Context.Name),
			helpers.JoinBlobPath(config.Context.EventID, config.Context.Name))
```

The input and output paths are joined with the module name... however when trying to use the outputted file in the next module this fails as the outputting modules name was "downloader" but the module downloading the file has the name "transcoder"

**Comment by lawrencegripper** [comment]
Right so I have a proposed fix and that is to remove the module name from the file path. As, when each module starts, a new UUID is generated which becomes it's eventID. 

If two modules outputted the same `clash.vid` file or a module was re-executed they would have a different eventID and so the files wouldn't clash. .... I think?!?

Going to test it but gone a bit snow blind on this one so need @jjcollinge  to validate this thinking when he's back on Monday.

**Comment by lawrencegripper** [comment]
That seems to have got it, will leave this open for Joni to validate I haven't broken anything with this fix.

**Comment by jjcollinge** [comment]
On mobile so can't really dive into the code. IIRC, the event ID is generated by the parent when it writes the event and creates the associated event metadata. Therefore, any module that processes that event will share the event ID (retries too). The only unique ID is the execution ID which is used to identify which module the insights came from. The initial idea was that we used the event ID to differentiate it from other events, and the module name / module type as there  should only ever be 1 module type to 1 event ID, and retries would just overwrite existing blob data. However, appreciate this would require more strictness around module naming!

**Comment by lawrencegripper** [comment]
Cheers for taking a look, don't worry about it for now we can catchup monday.

**Comment by lawrencegripper** [comment]
So reflecting on this, while my fix will have worked I think I'll have also broken any modules which create multiple events (they'll all get the same event id with my change). Need to look at how to make this work next week.

**Comment by lawrencegripper** [comment]
I'm using the SAS urls now in the preparer to download the files. This works.
