### ISSUE TITLE
Move sidecar to using file based system

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/ion#15]
Instead of using a REST based API between the sidecar and the module container this work looks to simplify this relationship by using a filebased approach. 

The sidecar would be responsible for identifying any input files and metadata required for the module processing and make them available to the module through a shared volume. The module would then write it's output data and events to defined location and the sidecar would by able to sync these files to the appropriate place and raise any required events.

**Comment by jjcollinge** [comment]
done in #34
