### ISSUE TITLE
Stop communication between sidecar and module

### ISSUE THREAD

**Issue by redkite1** [lawrencegripper/ion#18]
We already reduced the amount of communication between the sidecar and the module, we now only communicate in two cases:

1. module ask to the sidecar if it can runs (data on the fs are ready or not?)
2. module tell the sidecar it finished (data are ready to be read on the fs)

Why not going a step further and find a way to run/start the module only when everything is ready (data, config) and get notified that the module finished only when it really exit (a little bit as if we were doing a simple system.exec(...) and waiting it's end.

The **goal** is to make the module writers independent from the sidecar, I'd love that module never have to spoke/to care about sidecar.

**Comment by lawrencegripper** [comment]
Like this plan, will need the work to be completed moving the sidecar to a filebased approach in #15 before we look at this in more detail.

**Comment by lawrencegripper** [comment]
Done with the handler rewrite
