### ISSUE TITLE
Refactor structure of the project

### ISSUE THREAD

**Issue by redkite1** [lawrencegripper/ion#46]
We start to have more and more "application binary", maybe we should refactor and use the **ion/cmd** layout pattern which store all the commands (dispatcher, sidecar, frontapi, ...?) in a single folder and put all libraries and tools next to that **ion/cmd** folder.

Inspiration:

- https://github.com/golang-standards/project-layout
- https://github.com/golang/tools
- https://github.com/kubernetes/kubernetes/tree/master/cmd
- https://github.com/prometheus/prometheus/tree/master/cmd

**Comment by lawrencegripper** [comment]
Very much approve of this idea!
