### ISSUE TITLE
Integration test between sidecar and dispatcher

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/ion#69]
We currently don't have any integration tests that test for breaking changes between the sidecar and dispatcher.
For this we'd need a local dispatcher that can just run the tasks locally.

cc @lawrencegripper

**Comment by lawrencegripper** [comment]
To enable this I'm working on a Terraform template to deploy all the system pre-reqs:

- mongo (cosmos)
- amqp (servicebus)
- storage
- kubernetes

**Comment by lawrencegripper** [comment]
Terraform work and new script in `./tools/end2end-smoketest.sh` created. 

This will setup all the required infrastructure and deploy the frontapi, management api then install the downloader and transcoding module then submit a request to the frontpai with a new video. 

Manual work is required to investigate the output from the modules but I can't see an easy way around that.
