### ISSUE TITLE
Configure Kubernetes PullPolicy behaviour

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/ion#72]
Currently the container image pull policy behaviour in the Kubernetes provider is not configurable. In order to support using local container images rather than external we need to enable this.

Offending line:
https://github.com/lawrencegripper/ion/blob/b420401ad1d96c583a070fec253e59a15a24a78b/dispatcher/providers/kubernetes.go#L245

**Comment by lawrencegripper** [comment]
In pr #68 as `--job.pullalways`
