### ISSUE TITLE
Add log to applications insight hook

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/ion#8]
Add Logrus logging and Application Insight hooks to build dashboards to monitor jobs, events, data etc.

**Comment by lawrencegripper** [comment]
Dispatcher to log:
- Queue Depth
- In progress job count
- Last received message time
- Processing times for modules (avg, min, max) and individual video module run time (time per module per correlationid)
- Log trace for stdout from each module (optional turn on or off)
