### ISSUE TITLE
Proposal: Ion service side Management API

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/ion#84]
## What
This proposal outlines a potential server side component for Ion.
This component could be deployed to the cluster using helm and would expose a REST API that would allow you to perform operations against Ion jobs running in the cluster.

## Why?
This change would drastically improve the usability and developer experience of using and operating Ion.

This would enable the following scenarios:

**Creating a job**
Creating a new job by simply posting a configuration to the REST API without knowing anything else about the dispatcher or Kubernetes
```json
{
    "moduleImage": "dotjson/mymodule:1.2.3",
    "moduleName": "myModule",
    "eventsIn": [
        "face_detected"
    ],
    "eventsOut": [
        "face_cropped"
    ]
}
```
The server would then interpret this config and create a new Kubernetes POD specification for the Dispatcher (can steal from existing code) and publish it to Kubernetes. The server would add annotations to the pod that will be useful later on, such as module name, userId, createdAt, etc. Returning a unique ID to the user to lookup the job.

**Querying a job**
The user could then query the status of the job via the API which would return the current running status in Kubernetes as well as other statistics about it's execution (running time etc.).

**Querying all jobs**
The management API could also be used to list all of the currently running jobs in the cluster as well as the historic jobs and their status.

**Visualization and Management**
The API could then be used to build a web application which allows you to visualize and manage your Ion deployments from a UI.

![ion-ui](https://user-images.githubusercontent.com/7241190/39625452-5b8dffca-4f95-11e8-913a-fa4499501d14.PNG)
)

**Comment by jjcollinge** [comment]
As part of this work we'd like to limit the number of jobs any given dispatcher can dispatch at one time. We're going to publish all metrics to directly to Application Insights. We'll then also expose an internal liveness endpoint on the dispatcher that prints out the last timestamp of each loop iteration in the dispatcher to indicate that things are working OK.

**Comment by lawrencegripper** [comment]
In progress with #120
