### ISSUE TITLE
Optmize build process

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/ion#95]
Currently we run `dep ensure ...` in the makefile in order to run the tests, we then copy the vendor package into our build containers and run `dep ensure ...` again - this slows down the build process considerably. We can optimize this by only running in once on the host.

**Comment by lawrencegripper** [comment]
Doing this now as it's annoyingly slow now we have lots of different images

**Comment by lawrencegripper** [comment]
Done and also moved push.sh to pick up any `ion-*` images and tag and push them. It also now runs locally as long as you have set $DOCKER_USER variable.
